# Generated by Django 4.2.6 on 2023-10-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('channel', 'Kanal'), ('tashkent_group', 'Toshkent uchun guruh'), ('regions_group', 'Viloyatlar uchun guruh')], max_length=100)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone_number', models.CharField(max_length=100)),
                ('client_products', models.TextField()),
                ('client_products_images', models.CharField(blank=True, max_length=150, null=True)),
                ('client_products_wrapping_type', models.CharField(blank=True, max_length=250, null=True)),
                ('client_wrapped_products_images', models.CharField(blank=True, max_length=150, null=True)),
                ('client_products_price', models.CharField(max_length=400)),
                ('client_products_payment_status', models.CharField(max_length=100)),
                ('client_social_network', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=100)),
                ('delivery_date', models.CharField(max_length=200)),
                ('location', models.TextField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=300, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
