# Generated by Django 4.2.6 on 2023-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
    ]
