# Generated by Django 4.2.6 on 2023-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_orders_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_products_payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
