# Generated by Django 4.2.6 on 2023-11-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_orders_latitude_orders_longitude_alter_chats_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bot_admins',
            },
        ),
    ]
